# Generated by Django 5.2.3 on 2025-06-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('department', models.CharField(max_length=55)),
                ('reg_number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('major_subject', models.CharField(choices=[('Computer', 'Computer'), ('Physics', 'Physics'), ('Math', 'Math'), ('Bio', 'Bio')], max_length=55)),
            ],
        ),
    ]
